FROM debian:bullseye-slim
# FROM tinygo/tinygo:0.26.0

ENV DEBIAN_FRONTEND nointeractive
RUN apt-get update &&\
    apt-get install -y \
    gcc-avr \
    avr-libc \
    avrdude \
    wget \
    usbutils \
    git \
    curl \
    locales \
    whois \
    vim \
   	sudo \
    libncurses-dev \
    flex \
    bison \
    gperf \
    python \
    python3-serial \
    pip \
    binutils \
    cmake &&\
    apt-get clean &&\
    rm -fr /var/lib/apt/lists/*

ENV TINYGO_VERSION=0.26.0
RUN set -eux; \
    deb="tinygo_${TINYGO_VERSION}_arm64.deb"; \
    wget https://github.com/tinygo-org/tinygo/releases/download/v${TINYGO_VERSION}/$deb; \
    dpkg -i $deb; \
    rm $deb

ENV GOLANG_VERSION=1.18.8
RUN set -eux; \
    tar="go${GOLANG_VERSION}.linux-arm64.tar.gz"; \
    wget "https://go.dev/dl/$tar"; \
    rm -rf /usr/local/go; \
    tar -C /usr/local -xzf $tar; \
    rm $tar
RUN echo 'export PATH=$PATH:/usr/local/go/bin' > /etc/profile.d/go.sh

RUN git clone https://github.com/MakerAsia/kbide-esp-idf-platfrom-linuxarm64.git /usr/local/esp
RUN echo 'export PATH=$PATH:/usr/local/esp/tools/xtensa-esp32-elf/bin' > /etc/profile.d/esp.sh
RUN pip install esptool --system

RUN curl -fsSL https://code-server.dev/install.sh | sh

RUN set -eux; \
    sed -i -E 's/# (en_US.UTF-8)/\1/' /etc/locale.gen; \
    locale-gen
ENV LANG       en_US.UTF-8
ENV LANGUAGE   en_US:en
ENV LC_ALL     en_US.UTF-8

ENV VSCODE_USER       vscode
ENV VSCODE_PASSWORD   passwd
ENV VSCODE_GROUP      vscode
ENV VSCODE_HOME       /home/vscode
ENV VSCODE_UID        1000
ENV VSCODE_GID        1000
ENV VSCODE_GRANT_SUDO nopass
ENV VSCODE_PORT       8080

COPY ./entrypoint.sh /entrypoint.sh

RUN set -eux; \
    HOME=/etc/skel code-server --install-extension hediet.vscode-drawio; \
    HOME=/etc/skel code-server --install-extension golang.Go; \
    chmod -R go+rx /etc/skel

EXPOSE 8080

ENTRYPOINT ["/entrypoint.sh"]
